# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1474a129a524c930cf7ceaeaab10e19d4c498b9fff0071d26d1f43459f0855a7bb5398fc73a9c0a37b4f545e3c30dea8f446d8440cf62484a6ef29a03395ccc4

test:
  secret_key_base: 06070912ac4fdc96fee3c0cec44a6a75d7b2c3846d689588e13bbc2298666d136e9373603f4a550ae1e5e1b058162923bef2129d8ed9eb10fe6edde25126d176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
