Card.create!([
  {name: "cybersurfer", cost: 4, attack: 4, description: "what the computer in virtual reality enables us to do is to recalibrate ourselves so that we can start seeing those pieces of information that are invisible to us but have become important for us to understand. - douglas adams", action_text: "this dude just hacked your mainframe", image_file_name: "cybersurfer.gif", image_content_type: "image/gif", image_file_size: 110295, image_updated_at: "2017-03-29 02:29:36"},
  {name: "transcendence", cost: 4, attack: 4, description: "meditation is to dive all the way within, beyond thought, to the source of thought and pure consciousness. it enlarges the container, every time you transcend. when you come out, you come out refreshed, filled with energy and enthusiasm for life. david lynch", action_text: "deconstructing consciousness", image_file_name: "transcendence.gif", image_content_type: "image/gif", image_file_size: 89651, image_updated_at: "2017-03-29 04:00:39"},
  {name: "divine intervention", cost: 8, attack: 8, description: "warning: incoming game", action_text: "it’s raining giant cubes… we’re doomed", image_file_name: "divineintervention.gif", image_content_type: "image/gif", image_file_size: 135383, image_updated_at: "2017-03-29 03:53:03"},
  {name: "valerie", cost: 6, attack: 6, description: "the cube is an imitation of life itself - or even an improvement on life. - erno rubik", action_text: "quit makin a fool outta me", image_file_name: "valerie.gif", image_content_type: "image/gif", image_file_size: 129958, image_updated_at: "2017-03-29 04:01:06"},
  {name: "lost in space", cost: 3, attack: 3, description: "enlightenment is my tomorrow. it has no planes of sorrow hereby, my invitation: i do invite you to be of my space world. - sun ra", action_text: "danger, will robinson!", image_file_name: "lost-in-space.gif", image_content_type: "image/gif", image_file_size: 149355, image_updated_at: "2017-03-29 03:54:20"},
  {name: "spooky dude", cost: 4, attack: 4, description: "whose bones are these?", action_text: "you have been bespooked", image_file_name: "spookydude.gif", image_content_type: "image/gif", image_file_size: 98095, image_updated_at: "2017-03-29 03:59:02"},
  {name: "martian dude", cost: 1, attack: 1, description: "the martians are always coming - pkd", action_text: "close encounters of the rad kind", image_file_name: "martian-dude.gif", image_content_type: "image/gif", image_file_size: 123103, image_updated_at: "2017-03-29 03:55:51"},
  {name: "back", cost: nil, attack: nil, description: "", action_text: "", image_file_name: "backofcards357by500.gif", image_content_type: "image/gif", image_file_size: 126733, image_updated_at: "2017-03-29 04:26:24"},
  {name: "alien horizon", cost: 2, attack: 2, description: "we hold this myth to be potential, not self-evident but equational. another dimension of another kind of Living Life. - sun ra", action_text: "no man's sky", image_file_name: "alien-horizon.gif", image_content_type: "image/gif", image_file_size: 166891, image_updated_at: "2017-03-29 02:21:24"},
  {name: "yung isosceles", cost: 2, attack: 2, description: "hip-hop style pyramid man", action_text: "yung isosceles spits hot fire", image_file_name: "yung-isosceles.gif", image_content_type: "image/gif", image_file_size: 44954, image_updated_at: "2017-03-29 02:20:34"},
  {name: "ancient alien", cost: 3, attack: 3, description: "researchers believe that this is the most ancient of aliens. you may think that he is wearing a hat but that’s just what his head looks like.", action_text: "ancient alien explains it all", image_file_name: "ancient-alien.gif", image_content_type: "image/gif", image_file_size: 122803, image_updated_at: "2017-03-29 02:15:16"},
  {name: "colossus", cost: 6, attack: 6, description: "despite his menacing appearance, this is one gentle giant. just don’t get on his bad side or he’ll totally crush your bones. his only known weakness is kittens.", action_text: "your bones are like, totally crushed...", image_file_name: "colossus.gif", image_content_type: "image/gif", image_file_size: 128739, image_updated_at: "2017-03-29 02:16:19"},
  {name: "dawg", cost: 7, attack: 7, description: "check out this dog", action_text: "woof!", image_file_name: "dawg.gif", image_content_type: "image/gif", image_file_size: 150092, image_updated_at: "2017-03-29 02:16:46"},
  {name: "givenchy", cost: 5, attack: 5, description: "remembering that you are going to die is the best way i know to avoid the trap of thinking you have something to lose. you are already naked. there is no reason not to follow your heart. - steve jobs", action_text: "looks can kill", image_file_name: "givenchy.gif", image_content_type: "image/gif", image_file_size: 105951, image_updated_at: "2017-03-29 02:17:23"},
  {name: "viktor vaughn", cost: 2, attack: 2, description: "a killer who love children. one who is well-skilled in destruction, as well as building", action_text: "when he do a jam, fans break dancin' in the stands", image_file_name: "viktor-vaughn.gif", image_content_type: "image/gif", image_file_size: 92512, image_updated_at: "2017-03-29 02:17:58"},
  {name: "lil robot", cost: 1, attack: 1, description: "with regard to robots, in the early days of robots people said, ‘oh, let's build a robot' and what's the first thought? you make a robot look like a human and do human things. that's so 1950s. we are so past that. - neil degrasse tyson ", action_text: "lil robot kicks your shin. ouch.", image_file_name: "lil-robot.gif", image_content_type: "image/gif", image_file_size: 69733, image_updated_at: "2017-03-29 02:18:51"},
  {name: "secret tape", cost: 0, attack: 0, description: "these things are notoriously hard to find.", action_text: "you found the secret tape", image_file_name: "secret-tape.gif", image_content_type: "image/gif", image_file_size: 108482, image_updated_at: "2017-03-29 02:20:02"},
  {name: "polymorphic blob", cost: 3, attack: 3, description: "it's unclear what reality these creatures originate from or how they came to exist in our own.", action_text: "a sticky slap from an ambiguous appendage", image_file_name: "polymophic-blob2.gif", image_content_type: "image/gif", image_file_size: 94875, image_updated_at: "2017-03-29 02:22:14"},
  {name: "useless thought", cost: 0, attack: 0, description: "mr. madison, what you’ve just said is one of the most insanely idiotic things I have ever heard. at no point in your rambling, incoherent response were you even close to anything that could be considered a rational thought. everyone in this room is now dumber for having listened to it. i award you no points, and may god have mercy on your soul.", action_text: "how can mirrors be real if our eyes aren't real?", image_file_name: "useless-thought.gif", image_content_type: "image/gif", image_file_size: 126164, image_updated_at: "2017-03-29 02:27:00"},
  {name: "mu-222", cost: 5, attack: 5, description: "as man himself becomes more metal, there's something comforting about the ease at which the mecha pilot maneuvers his machine.", action_text: "pew pew pew pew", image_file_name: "mu222.gif", image_content_type: "image/gif", image_file_size: 92357, image_updated_at: "2017-03-29 02:28:02"},
  {name: "ancient disk", cost: 3, attack: 3, description: "an old world artifact said to contain classical music audio files by renowned artists such as blink-182.", action_text: "you are overcome with nostalgia", image_file_name: "ancientdisk.gif", image_content_type: "image/gif", image_file_size: 56119, image_updated_at: "2017-03-29 02:28:54"}
])

MyCard.create!([
  {user_id: 5, card_id: 56, deck: true, status: nil},
  {user_id: 6, card_id: 56, deck: true, status: nil},
  {user_id: 5, card_id: 61, deck: true, status: nil},
  {user_id: 6, card_id: 61, deck: true, status: nil},
  {user_id: 5, card_id: 57, deck: true, status: nil},
  {user_id: 6, card_id: 57, deck: true, status: nil},
  {user_id: 5, card_id: 62, deck: true, status: nil},
  {user_id: 6, card_id: 62, deck: true, status: nil},
  {user_id: 5, card_id: 58, deck: true, status: nil},
  {user_id: 6, card_id: 58, deck: true, status: nil},
  {user_id: 5, card_id: 60, deck: true, status: nil},
  {user_id: 6, card_id: 60, deck: true, status: nil},
  {user_id: 5, card_id: 59, deck: true, status: nil},
  {user_id: 6, card_id: 59, deck: true, status: nil},
  {user_id: 5, card_id: 41, deck: true, status: nil},
  {user_id: 6, card_id: 41, deck: true, status: nil},
  {user_id: 5, card_id: 42, deck: true, status: nil},
  {user_id: 6, card_id: 42, deck: true, status: nil},
  {user_id: 5, card_id: 43, deck: true, status: nil},
  {user_id: 6, card_id: 43, deck: true, status: nil},
  {user_id: 5, card_id: 44, deck: true, status: nil},
  {user_id: 6, card_id: 44, deck: true, status: nil},
  {user_id: 5, card_id: 45, deck: true, status: nil},
  {user_id: 6, card_id: 45, deck: true, status: nil},
  {user_id: 5, card_id: 46, deck: true, status: nil},
  {user_id: 6, card_id: 46, deck: true, status: nil},
  {user_id: 5, card_id: 47, deck: true, status: nil},
  {user_id: 6, card_id: 47, deck: true, status: nil},
  {user_id: 5, card_id: 48, deck: true, status: nil},
  {user_id: 6, card_id: 48, deck: true, status: nil},
  {user_id: 5, card_id: 49, deck: true, status: nil},
  {user_id: 6, card_id: 49, deck: true, status: nil},
  {user_id: 5, card_id: 50, deck: true, status: nil},
  {user_id: 6, card_id: 50, deck: true, status: nil},
  {user_id: 5, card_id: 53, deck: true, status: nil},
  {user_id: 6, card_id: 53, deck: true, status: nil},
  {user_id: 5, card_id: 54, deck: true, status: nil},
  {user_id: 6, card_id: 54, deck: true, status: nil},
  {user_id: 5, card_id: 55, deck: true, status: nil},
  {user_id: 6, card_id: 55, deck: true, status: nil},
  {user_id: 7, card_id: 56, deck: true, status: nil},
  {user_id: 7, card_id: 61, deck: true, status: nil},
  {user_id: 7, card_id: 57, deck: true, status: nil},
  {user_id: 7, card_id: 62, deck: true, status: nil},
  {user_id: 7, card_id: 58, deck: true, status: nil},
  {user_id: 7, card_id: 60, deck: true, status: nil},
  {user_id: 7, card_id: 59, deck: true, status: nil},
  {user_id: 7, card_id: 63, deck: true, status: nil},
  {user_id: 7, card_id: 49, deck: true, status: nil},
  {user_id: 7, card_id: 48, deck: true, status: nil},
  {user_id: 7, card_id: 41, deck: true, status: nil},
  {user_id: 7, card_id: 42, deck: true, status: nil},
  {user_id: 7, card_id: 43, deck: true, status: nil},
  {user_id: 7, card_id: 44, deck: true, status: nil},
  {user_id: 7, card_id: 45, deck: true, status: nil},
  {user_id: 7, card_id: 46, deck: true, status: nil},
  {user_id: 7, card_id: 47, deck: true, status: nil},
  {user_id: 7, card_id: 50, deck: true, status: nil},
  {user_id: 7, card_id: 53, deck: true, status: nil},
  {user_id: 7, card_id: 54, deck: true, status: nil},
  {user_id: 7, card_id: 55, deck: true, status: nil},
  {user_id: 8, card_id: 56, deck: true, status: nil},
  {user_id: 8, card_id: 61, deck: true, status: nil},
  {user_id: 8, card_id: 57, deck: true, status: nil},
  {user_id: 8, card_id: 62, deck: true, status: nil},
  {user_id: 8, card_id: 58, deck: true, status: nil},
  {user_id: 8, card_id: 60, deck: true, status: nil},
  {user_id: 8, card_id: 59, deck: true, status: nil},
  {user_id: 8, card_id: 49, deck: true, status: nil},
  {user_id: 8, card_id: 48, deck: true, status: nil},
  {user_id: 8, card_id: 41, deck: true, status: nil},
  {user_id: 8, card_id: 42, deck: true, status: nil},
  {user_id: 8, card_id: 43, deck: true, status: nil},
  {user_id: 8, card_id: 44, deck: true, status: nil},
  {user_id: 8, card_id: 45, deck: true, status: nil},
  {user_id: 8, card_id: 46, deck: true, status: nil},
  {user_id: 8, card_id: 47, deck: true, status: nil},
  {user_id: 8, card_id: 50, deck: true, status: nil},
  {user_id: 8, card_id: 53, deck: true, status: nil},
  {user_id: 8, card_id: 54, deck: true, status: nil},
  {user_id: 8, card_id: 55, deck: true, status: nil}
])
User.create!([
  {name: "playerone", email: "playerone@email.com", password_digest: "$2a$10$yMwVK3GozVbqVDkysYR2WOAjdXQO0JXuhAuqrCgNMMrNqM8/bvXNC", bio: nil, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {name: "playertwo", email: "playertwo@email.com", password_digest: "$2a$10$pnwszbR0imggML8S6ac4Leadg3s6OVFFP4FrmHrXJ672AfuvbO8WC", bio: nil, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {name: "dude", email: "dude@email.com", password_digest: "$2a$10$CChy/EVVTX8gNbT5oV7gNOc6uaql.WPjkht4emECK8aSrL11oXqwq", bio: nil, avatar_file_name: "73698dbb21b19d40a58f9e6f49b15656.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 444231, avatar_updated_at: "2017-03-17 01:13:34"},
  {name: "tuff guy", email: "tuff@email.com", password_digest: "$2a$10$3WWgYdoEq1CVRAJCPcO1bOkyCU/z3fR.2XMBaUvUG8aNSZapAKkgy", bio: nil, avatar_file_name: "IMG_2567.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 131322, avatar_updated_at: "2017-03-17 02:03:37"},
  {name: "player2", email: "googlyeyes@email.com", password_digest: "$2a$10$yhWN6r3Qx6dWiosGHUTqaOL4j.P.1dWGKyvtn9GXy5BUTb8UN1LRW", bio: nil, avatar_file_name: "IMG_3954.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 963653, avatar_updated_at: "2017-03-29 04:13:39"},
  {name: "dude", email: "dude@email.com", password_digest: "$2a$10$TaSJ8cA6kzbMHbtzEMPC4ufaGcY84PLGOmH5OW04pnEbF3rzH0dOC", bio: nil, avatar_file_name: "12821628_10206442162069707_6699799519415416957_n.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 155712, avatar_updated_at: "2017-04-24 01:41:39"},
  {name: "dude 2", email: "dude2@email.com", password_digest: "$2a$10$nP3CETxAG6sBfKMzKNErUuQZlpHaW9ueq3USqVH6no6wyeQ6d5P.6", bio: nil, avatar_file_name: "artifact-from-illinois-caves.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 2153745, avatar_updated_at: "2017-04-24 01:43:54"},
  {name: "player1", email: "player1@email.com", password_digest: "$2a$10$AWzWxta/157wF7eMqAArmuCh8Is9YXftm3FX8LGXV8Gjovnq0SYxG", bio: nil, avatar_file_name: "myavi.gif", avatar_content_type: "image/gif", avatar_file_size: 13104, avatar_updated_at: "2017-03-29 04:05:19"}
])
